//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.488
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTFramework.Utils.ReflectionUtil.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MTFramework.Utils.ReflectionUtil.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 参数:&apos;fieldInfo&apos;不能为 Null 的本地化字符串。
        /// </summary>
        internal static string ArgumentFieldInfoIsNullError {
            get {
                return ResourceManager.GetString("ArgumentFieldInfoIsNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数:&apos;propertyInfo&apos;不能为 Null 的本地化字符串。
        /// </summary>
        internal static string ArgumentPropertyInfoIsNull {
            get {
                return ResourceManager.GetString("ArgumentPropertyInfoIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数:&apos;propertyOrFieldName&apos;不能为 Null 的本地化字符串。
        /// </summary>
        internal static string ArgumentPropertyOrFieldNameIsNull {
            get {
                return ResourceManager.GetString("ArgumentPropertyOrFieldNameIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数:&apos;type&apos;不能为 Null 的本地化字符串。
        /// </summary>
        internal static string ArgumentTypeIsNullError {
            get {
                return ResourceManager.GetString("ArgumentTypeIsNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持带参数的构造函数 的本地化字符串。
        /// </summary>
        internal static string ConstructorsWithParametersNotSupported {
            get {
                return ResourceManager.GetString("ConstructorsWithParametersNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建Object错误（Type:{0}) 的本地化字符串。
        /// </summary>
        internal static string CreateObjectError {
            get {
                return ResourceManager.GetString("CreateObjectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认构造函数 的本地化字符串。
        /// </summary>
        internal static string DefaultConstructor {
            get {
                return ResourceManager.GetString("DefaultConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字典中有重复的Key值.(dictionary:{0} key:{1}) 的本地化字符串。
        /// </summary>
        internal static string DictionaryKeyDuplication {
            get {
                return ResourceManager.GetString("DictionaryKeyDuplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制失败 的本地化字符串。
        /// </summary>
        internal static string FieldCopyFailed {
            get {
                return ResourceManager.GetString("FieldCopyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在类型 {0} 中没有找到 {1}) 属性标记 的本地化字符串。
        /// </summary>
        internal static string KeyPropertyNotFound {
            get {
                return ResourceManager.GetString("KeyPropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调用方法失败 的本地化字符串。
        /// </summary>
        internal static string MethodCallFailed {
            get {
                return ResourceManager.GetString("MethodCallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未执行 的本地化字符串。
        /// </summary>
        internal static string MethodNotImplemented {
            get {
                return ResourceManager.GetString("MethodNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在 {0} 中未找到 {1} 对象 的本地化字符串。
        /// </summary>
        internal static string NotFoundMemberInObject {
            get {
                return ResourceManager.GetString("NotFoundMemberInObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该父类型不是来源类型的父类型.(type:{0} Parent Type:{1}) 的本地化字符串。
        /// </summary>
        internal static string ParentTypeError {
            get {
                return ResourceManager.GetString("ParentTypeError", resourceCulture);
            }
        }
    }
}
