//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDFTron.SilverDox.Samples.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDFTron.SilverDox.Samples.Resources.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ellipse.
        /// </summary>
        public static string AnnotationCreateEllipseToolTip {
            get {
                return ResourceManager.GetString("AnnotationCreateEllipseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Hand.
        /// </summary>
        public static string AnnotationCreateFreeHandToolTip {
            get {
                return ResourceManager.GetString("AnnotationCreateFreeHandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string AnnotationCreateLineToolTip {
            get {
                return ResourceManager.GetString("AnnotationCreateLineToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle.
        /// </summary>
        public static string AnnotationCreateRectangleToolTip {
            get {
                return ResourceManager.GetString("AnnotationCreateRectangleToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sticky Note.
        /// </summary>
        public static string AnnotationCreateStickyToolTip {
            get {
                return ResourceManager.GetString("AnnotationCreateStickyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Highlight.
        /// </summary>
        public static string AnnotationCreateTextHighlightToolTip {
            get {
                return ResourceManager.GetString("AnnotationCreateTextHighlightToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Strikeout.
        /// </summary>
        public static string AnnotationCreateTextStrikeoutToolTip {
            get {
                return ResourceManager.GetString("AnnotationCreateTextStrikeoutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Underline.
        /// </summary>
        public static string AnnotationCreateTextUnderlineToolTip {
            get {
                return ResourceManager.GetString("AnnotationCreateTextUnderlineToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string AnnotationEditToolTip {
            get {
                return ResourceManager.GetString("AnnotationEditToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case sensitive.
        /// </summary>
        public static string CaseSensitive {
            get {
                return ResourceManager.GetString("CaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuous.
        /// </summary>
        public static string Continuous {
            get {
                return ResourceManager.GetString("Continuous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Annotation.
        /// </summary>
        public static string CopyAnnotationCommand {
            get {
                return ResourceManager.GetString("CopyAnnotationCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string CopyCommand {
            get {
                return ResourceManager.GetString("CopyCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover Facing.
        /// </summary>
        public static string CoverFacing {
            get {
                return ResourceManager.GetString("CoverFacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover Facing Continuous.
        /// </summary>
        public static string CoverFacingContinuous {
            get {
                return ResourceManager.GetString("CoverFacingContinuous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current page number.
        /// </summary>
        public static string CurrentPageToolTip {
            get {
                return ResourceManager.GetString("CurrentPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entire Document Searched.
        /// </summary>
        public static string DocumentSearchedCaption {
            get {
                return ResourceManager.GetString("DocumentSearchedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entire document searched. No more matches were found..
        /// </summary>
        public static string DocumentSearchedMessage {
            get {
                return ResourceManager.GetString("DocumentSearchedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whole Document Search.
        /// </summary>
        public static string DocumentSearchToolTip {
            get {
                return ResourceManager.GetString("DocumentSearchToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading document.
        /// </summary>
        public static string ErrorLoadingDocument {
            get {
                return ResourceManager.GetString("ErrorLoadingDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facing.
        /// </summary>
        public static string Facing {
            get {
                return ResourceManager.GetString("Facing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facing Continuous.
        /// </summary>
        public static string FacingContinuous {
            get {
                return ResourceManager.GetString("FacingContinuous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to first page.
        /// </summary>
        public static string FirstPageToolTip {
            get {
                return ResourceManager.GetString("FirstPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit Page.
        /// </summary>
        public static string FitPageCommand {
            get {
                return ResourceManager.GetString("FitPageCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit to page.
        /// </summary>
        public static string FitPageToolTip {
            get {
                return ResourceManager.GetString("FitPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit Width.
        /// </summary>
        public static string FitWidthCommand {
            get {
                return ResourceManager.GetString("FitWidthCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit to width.
        /// </summary>
        public static string FitWidthToolTip {
            get {
                return ResourceManager.GetString("FitWidthToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full-screen mode.
        /// </summary>
        public static string FullScreenToolTip {
            get {
                return ResourceManager.GetString("FullScreenToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide outline navigation.
        /// </summary>
        public static string HideOutlineToolTip {
            get {
                return ResourceManager.GetString("HideOutlineToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to last page.
        /// </summary>
        public static string LastPageToolTip {
            get {
                return ResourceManager.GetString("LastPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the drop-down menu to select a page presentation mode.
        /// </summary>
        public static string LayoutButtonToolTip {
            get {
                return ResourceManager.GetString("LayoutButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to next page.
        /// </summary>
        public static string NextPageToolTip {
            get {
                return ResourceManager.GetString("NextPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of pages.
        /// </summary>
        public static string NumberOfPagesToolTip {
            get {
                return ResourceManager.GetString("NumberOfPagesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open local file.
        /// </summary>
        public static string OpenFileToolTip {
            get {
                return ResourceManager.GetString("OpenFileToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlines.
        /// </summary>
        public static string OutlinesToolTip {
            get {
                return ResourceManager.GetString("OutlinesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0}.
        /// </summary>
        public static string PageStringFormat {
            get {
                return ResourceManager.GetString("PageStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan Tool.
        /// </summary>
        public static string PanToolCommand {
            get {
                return ResourceManager.GetString("PanToolCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan tool.
        /// </summary>
        public static string PanToolTip {
            get {
                return ResourceManager.GetString("PanToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Annotation.
        /// </summary>
        public static string PasteAnnotationCommand {
            get {
                return ResourceManager.GetString("PasteAnnotationCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin tool bar.
        /// </summary>
        public static string PinToolbarToolTip {
            get {
                return ResourceManager.GetString("PinToolbarToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to previous page.
        /// </summary>
        public static string PreviousPageToolTip {
            get {
                return ResourceManager.GetString("PreviousPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print document.
        /// </summary>
        public static string PrintToolTip {
            get {
                return ResourceManager.GetString("PrintToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string RedoAnnotationCommand {
            get {
                return ResourceManager.GetString("RedoAnnotationCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Annotation.
        /// </summary>
        public static string RemoveAnnotationCommand {
            get {
                return ResourceManager.GetString("RemoveAnnotationCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate Pages CounterClockwise.
        /// </summary>
        public static string RotateCCWToolTip {
            get {
                return ResourceManager.GetString("RotateCCWToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate Pages Clockwise.
        /// </summary>
        public static string RotateCWToolTip {
            get {
                return ResourceManager.GetString("RotateCWToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search text.
        /// </summary>
        public static string SearchTextToolTip {
            get {
                return ResourceManager.GetString("SearchTextToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Tool.
        /// </summary>
        public static string SelectToolCommand {
            get {
                return ResourceManager.GetString("SelectToolCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show outline navigation.
        /// </summary>
        public static string ShowOutlineToolTip {
            get {
                return ResourceManager.GetString("ShowOutlineToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For security purposes, Silverlight restricts keyboard access during full-screen mode..
        /// </summary>
        public static string SilverlightKeyboardRestriction {
            get {
                return ResourceManager.GetString("SilverlightKeyboardRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Page.
        /// </summary>
        public static string SinglePage {
            get {
                return ResourceManager.GetString("SinglePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Not Found.
        /// </summary>
        public static string TextNotFoundCaption {
            get {
                return ResourceManager.GetString("TextNotFoundCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified text was not found..
        /// </summary>
        public static string TextNotFoundMessage {
            get {
                return ResourceManager.GetString("TextNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text selection tool.
        /// </summary>
        public static string TextSelectToolTip {
            get {
                return ResourceManager.GetString("TextSelectToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnails.
        /// </summary>
        public static string ThumbnailsToolTip {
            get {
                return ResourceManager.GetString("ThumbnailsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string UndoAnnotationCommand {
            get {
                return ResourceManager.GetString("UndoAnnotationCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has occured..
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpin tool bar.
        /// </summary>
        public static string UnpinToolbarToolTip {
            get {
                return ResourceManager.GetString("UnpinToolbarToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whole word only.
        /// </summary>
        public static string WholeWord {
            get {
                return ResourceManager.GetString("WholeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom In.
        /// </summary>
        public static string ZoomInCommand {
            get {
                return ResourceManager.GetString("ZoomInCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Out.
        /// </summary>
        public static string ZoomOutCommand {
            get {
                return ResourceManager.GetString("ZoomOutCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string ZoomToolTip {
            get {
                return ResourceManager.GetString("ZoomToolTip", resourceCulture);
            }
        }
    }
}
