//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTFramework.CreaditTerm.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MTFramework.CreaditTerm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 从开出发票日起,不超过{0}天结账; 的本地化字符串。
        /// </summary>
        public static string BaseDay_IN_Title {
            get {
                return ResourceManager.GetString("BaseDay_IN_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开出发票日结账; 的本地化字符串。
        /// </summary>
        public static string BaseDay_IN_Zero {
            get {
                return ResourceManager.GetString("BaseDay_IN_Zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从开出银行信用证日起,不超过{0}天结账; 的本地化字符串。
        /// </summary>
        public static string BaseDay_LC_Title {
            get {
                return ResourceManager.GetString("BaseDay_LC_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开出银行信用证日结账; 的本地化字符串。
        /// </summary>
        public static string BaseDay_LC_Zero {
            get {
                return ResourceManager.GetString("BaseDay_LC_Zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从收货日起,不超过{0}天结账; 的本地化字符串。
        /// </summary>
        public static string BaseDay_RP_Title {
            get {
                return ResourceManager.GetString("BaseDay_RP_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收货日结账; 的本地化字符串。
        /// </summary>
        public static string BaseDay_RP_Zero {
            get {
                return ResourceManager.GetString("BaseDay_RP_Zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从第一批货装运日起,不超过{0}天结账; 的本地化字符串。
        /// </summary>
        public static string BaseDay_SH_Title {
            get {
                return ResourceManager.GetString("BaseDay_SH_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第一批货装运日结账; 的本地化字符串。
        /// </summary>
        public static string BaseDay_SH_Zero {
            get {
                return ResourceManager.GetString("BaseDay_SH_Zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Code 格式错误! 的本地化字符串。
        /// </summary>
        public static string CodeError {
            get {
                return ResourceManager.GetString("CodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}日 的本地化字符串。
        /// </summary>
        public static string CutOffDay_Day {
            get {
                return ResourceManager.GetString("CutOffDay_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 月底 的本地化字符串。
        /// </summary>
        public static string CutOffDay_Last {
            get {
                return ResourceManager.GetString("CutOffDay_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 、 的本地化字符串。
        /// </summary>
        public static string CutOffDay_Sign {
            get {
                return ResourceManager.GetString("CutOffDay_Sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该公司是每月的{0}结账; 的本地化字符串。
        /// </summary>
        public static string CutOffDay_Title {
            get {
                return ResourceManager.GetString("CutOffDay_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 星期五 的本地化字符串。
        /// </summary>
        public static string Delay_Fri {
            get {
                return ResourceManager.GetString("Delay_Fri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 星期一 的本地化字符串。
        /// </summary>
        public static string Delay_Mon {
            get {
                return ResourceManager.GetString("Delay_Mon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 星期六 的本地化字符串。
        /// </summary>
        public static string Delay_Sat {
            get {
                return ResourceManager.GetString("Delay_Sat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 星期日 的本地化字符串。
        /// </summary>
        public static string Delay_Sun {
            get {
                return ResourceManager.GetString("Delay_Sun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 星期四 的本地化字符串。
        /// </summary>
        public static string Delay_Thur {
            get {
                return ResourceManager.GetString("Delay_Thur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如果遇到不是{0},则顺延至下一个{0}; 的本地化字符串。
        /// </summary>
        public static string Delay_Title {
            get {
                return ResourceManager.GetString("Delay_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 星期二 的本地化字符串。
        /// </summary>
        public static string Delay_Tue {
            get {
                return ResourceManager.GetString("Delay_Tue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作日 的本地化字符串。
        /// </summary>
        public static string Delay_W {
            get {
                return ResourceManager.GetString("Delay_W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 星期三 的本地化字符串。
        /// </summary>
        public static string Delay_Wed {
            get {
                return ResourceManager.GetString("Delay_Wed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 或 的本地化字符串。
        /// </summary>
        public static string OR {
            get {
                return ResourceManager.GetString("OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ^&lt;?[a-zA-Z]+\d+(@\d+(,\d+)*)?(/[a-zA-Z]+)?&gt;?$ 的本地化字符串。
        /// </summary>
        public static string RegexPattern {
            get {
                return ResourceManager.GetString("RegexPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}或{1} 的本地化字符串。
        /// </summary>
        public static string XOR {
            get {
                return ResourceManager.GetString("XOR", resourceCulture);
            }
        }
    }
}
